"""Update models with start date and uploaded files relationship

Revision ID: 63a8a40ec8e9
Revises: db0b7c3dbc1f
Create Date: 2024-09-17 10:51:16.219976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a8a40ec8e9'
down_revision = 'db0b7c3dbc1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
