"""Update Employee table with necessary fields

Revision ID: db0b7c3dbc1f
Revises: ca0b0c720b44
Create Date: 2024-09-17 10:45:46.653922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db0b7c3dbc1f'
down_revision = 'ca0b0c720b44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('phone_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('address', sa.String(), nullable=False))
        batch_op.drop_column('holidays_taken')
        batch_op.drop_column('days_absent')
        batch_op.drop_column('advanced_payment')
        batch_op.drop_column('salary_after')
        batch_op.drop_column('extra_hours_1_5')
        batch_op.drop_column('extra_hours')
        batch_op.drop_column('extra_days')
        batch_op.drop_column('hours_absent')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours_absent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('extra_days', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('extra_hours', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('extra_hours_1_5', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('salary_after', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('advanced_payment', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('days_absent', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('holidays_taken', sa.INTEGER(), nullable=True))
        batch_op.drop_column('address')
        batch_op.drop_column('phone_number')
        batch_op.drop_column('id_number')

    # ### end Alembic commands ###
